/* C Abstract Syntax Implementation generated by the BNF Converter. */

#include <stdio.h>
#include <stdlib.h>
#include "Absyn.h"

/********************   Prog    ********************/

Program make_Prog(ListExp p1)
{
    Program tmp = (Program) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating Prog!\n");
        exit(1);
    }
    tmp->kind = is_Prog;
    tmp->u.prog_.listexp_ = p1;
    return tmp;
}

/********************   ListExp    ********************/

ListExp make_ListExp(Exp p1, ListExp p2)
{
    ListExp tmp = (ListExp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ListExp!\n");
        exit(1);
    }
    tmp->exp_ = p1;
    tmp->listexp_ = p2;
    return tmp;
}

/********************   EAbs    ********************/

Exp make_EAbs(Id p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EAbs!\n");
        exit(1);
    }
    tmp->kind = is_EAbs;
    tmp->u.eabs_.id_ = p1;
    tmp->u.eabs_.exp_ = p2;
    return tmp;
}

/********************   EIf    ********************/

Exp make_EIf(Exp p1, Exp p2, Exp p3, Exp p4)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EIf!\n");
        exit(1);
    }
    tmp->kind = is_EIf;
    tmp->u.eif_.exp_1 = p1;
    tmp->u.eif_.exp_2 = p2;
    tmp->u.eif_.exp_3 = p3;
    tmp->u.eif_.exp_4 = p4;
    return tmp;
}

/********************   ELet    ********************/

Exp make_ELet(Id p1, Exp p2, Exp p3)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ELet!\n");
        exit(1);
    }
    tmp->kind = is_ELet;
    tmp->u.elet_.id_ = p1;
    tmp->u.elet_.exp_1 = p2;
    tmp->u.elet_.exp_2 = p3;
    return tmp;
}

/********************   ERec    ********************/

Exp make_ERec(Id p1, Exp p2, Exp p3)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ERec!\n");
        exit(1);
    }
    tmp->kind = is_ERec;
    tmp->u.erec_.id_ = p1;
    tmp->u.erec_.exp_1 = p2;
    tmp->u.erec_.exp_2 = p3;
    return tmp;
}

/********************   EHd    ********************/

Exp make_EHd(Exp p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EHd!\n");
        exit(1);
    }
    tmp->kind = is_EHd;
    tmp->u.ehd_.exp_ = p1;
    return tmp;
}

/********************   ETl    ********************/

Exp make_ETl(Exp p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ETl!\n");
        exit(1);
    }
    tmp->kind = is_ETl;
    tmp->u.etl_.exp_ = p1;
    return tmp;
}

/********************   ELE    ********************/

Exp make_ELE(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ELE!\n");
        exit(1);
    }
    tmp->kind = is_ELE;
    tmp->u.ele_.exp_1 = p1;
    tmp->u.ele_.exp_2 = p2;
    return tmp;
}

/********************   EPlus    ********************/

Exp make_EPlus(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EPlus!\n");
        exit(1);
    }
    tmp->kind = is_EPlus;
    tmp->u.eplus_.exp_1 = p1;
    tmp->u.eplus_.exp_2 = p2;
    return tmp;
}

/********************   EMinus    ********************/

Exp make_EMinus(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EMinus!\n");
        exit(1);
    }
    tmp->kind = is_EMinus;
    tmp->u.eminus_.exp_1 = p1;
    tmp->u.eminus_.exp_2 = p2;
    return tmp;
}

/********************   ETimes    ********************/

Exp make_ETimes(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ETimes!\n");
        exit(1);
    }
    tmp->kind = is_ETimes;
    tmp->u.etimes_.exp_1 = p1;
    tmp->u.etimes_.exp_2 = p2;
    return tmp;
}

/********************   EApp    ********************/

Exp make_EApp(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EApp!\n");
        exit(1);
    }
    tmp->kind = is_EApp;
    tmp->u.eapp_.exp_1 = p1;
    tmp->u.eapp_.exp_2 = p2;
    return tmp;
}

/********************   ENil    ********************/

Exp make_ENil()
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ENil!\n");
        exit(1);
    }
    tmp->kind = is_ENil;
    return tmp;
}

/********************   ECons    ********************/

Exp make_ECons(Exp p1, Exp p2)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating ECons!\n");
        exit(1);
    }
    tmp->kind = is_ECons;
    tmp->u.econs_.exp_1 = p1;
    tmp->u.econs_.exp_2 = p2;
    return tmp;
}

/********************   EInt    ********************/

Exp make_EInt(Integer p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EInt!\n");
        exit(1);
    }
    tmp->kind = is_EInt;
    tmp->u.eint_.integer_ = p1;
    return tmp;
}

/********************   EVar    ********************/

Exp make_EVar(Id p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EVar!\n");
        exit(1);
    }
    tmp->kind = is_EVar;
    tmp->u.evar_.id_ = p1;
    return tmp;
}

/********************   EFix    ********************/

Exp make_EFix(Exp p1)
{
    Exp tmp = (Exp) malloc(sizeof(*tmp));
    if (!tmp)
    {
        fprintf(stderr, "Error: out of memory when allocating EFix!\n");
        exit(1);
    }
    tmp->kind = is_EFix;
    tmp->u.efix_.exp_ = p1;
    return tmp;
}
